import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const name = searchParams.get('name');
  
  if (!name) {
    return new NextResponse('Image name required', { status: 400 });
  }

  // We are serving images generated by the Nano Banana model and saved in the artifacts folder.
  const filePath = `C:/Users/a/.gemini/antigravity/brain/78fcceb2-e8c1-4eb4-8f38-c7c55f3c3a5d/${name}`;
  
  try {
    const fileBuffer = fs.readFileSync(filePath);
    return new NextResponse(fileBuffer, {
      headers: { 
        'Content-Type': 'image/png',
        'Cache-Control': 'public, max-age=31536000, immutable'
      }
    });
  } catch (err) {
    return new NextResponse('Image not found', { status: 404 });
  }
}
